build:
  R CMD build .

install target=default_target:
  R CMD INSTALL {{target}}

document:
  Rscript -e "roxygen2::roxygenise()"

check: document build
  R CMD check --as-cran $(roxido src_pkg_filename)

default_target := "."
