build:
  R CMD build .

install target=default_target:
  R CMD INSTALL {{target}}

document:
  Rscript -e 'roxygen2::roxygenise()'

vignette:
  cd vignettes; Rscript -e 'rmarkdown::render("qslice.Rmd")'

check: document build
  R CMD check --as-cran $(roxido src_pkg_filename)

default_target := "."
